# Generated by Django 4.2 on 2023-04-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Feriado')),
                ('dia', models.IntegerField(verbose_name='Data')),
                ('mes', models.IntegerField(verbose_name='Mes')),
            ],
        ),
    ]
